sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"
before_install:
  - npm install -g grunt-cli
install: npm install
before_script: grunt build
notifications:
  email:
    - snowyu.lee@gmail.com

