sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
notifications:
  email:
    - snowyu.lee@gmail.com

